### ISSUE TITLE
你好，冒昧打扰了！

### ISSUE THREAD

**Issue by Yichengxuan** [quzusheng/WowAttackHelper#1]
你好，打扰你了。请问下这个脚本要如何安装呢？请问是否有Window下运行的脚本？

**Comment by quzusheng** [comment]
脚本是在Mac环境下写的，一些判断程序是否运行的代码是不能在Windows下运行的。但是游戏的逻辑逻辑稍微改下是可以在Windows运行的，但是你得改下几个关键的判断，比如攻击距离判断的函数，释放技能等等，逻辑很简单。
关于如何环境配置，你只需要安排pthon3，以及https://pyautogui.readthedocs.io/en/latest/install.html这个库就好，它是跨平台的

**Comment by Yichengxuan** [comment]
好的，非常感谢！
