### ISSUE TITLE
windows10 一直安装不上AppKit

### ISSUE THREAD

**Issue by lux182** [quzusheng/WowAttackHelper#2]
device.c
      c:\users\me\appdata\local\temp\pip-install-dizgglhx\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by lux182** [comment]
你好 ，我用其他的方案windows解决了

**Comment by jsnjfz** [comment]
> 你好 ，我用其他的方案windows解决了

请问是用什么方法解决的呢
